name: 'influconnect'

services:
  # Postgres DB
  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=modelshare
      - POSTGRES_DB=influconnect
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - influconnect-network

  # Redis
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./redis/data:/data
  #   networks:
  #     - influconnect-network

  # PGAdmin
  # pgadmin:
  #   image: dpage/pgadmin4:8.8
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=influconnect4@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   networks:
  #     - influconnect-network

networks:
  influconnect-network:
    driver: bridge

volumes:
  pgdata:
  # pgadmin_data:
